### ISSUE TITLE
Expression differentiation with constants

### ISSUE THREAD

**Issue by Tarlan0001** [chakravala/Reduce.jl#15]
Is it possible to differentiate and expression `C*(x+y)` by `x`, showing that `C` is a constant?

**Comment by chakravala** [comment]
Do you mean like this?
```Julia
julia> using Reduce
Reduce (Free CSL version, revision 4590), 11-May-18 ...

julia> Algebra.df( :(c*(x+y)), :x)
:c
```
note that REDUCE is not set to be case sensitive, so `C` will be returned as `c`.

**Comment by Tarlan0001** [comment]
How did it recognize that `c` is constant but `y` is variable?

**Comment by chakravala** [comment]
It is treated as [partial differentiation](https://en.wikipedia.org/wiki/Partial_derivative), i.e. `x` is declared as the variable and the others are treated constant.
