### ISSUE TITLE
Error when trying to build package Reduce.

### ISSUE THREAD

**Issue by kirtsar** [chakravala/Reduce.jl#18]
```
julia> Pkg.build("Reduce")
  Building Reduce → `~/.julia/packages/Reduce/YlFQE/deps/build.log`
┌ Error: Error building `Reduce`: 
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   746  100   746    0     0    490      0  0:00:01  0:00:01 --:--:--   490
│ 
│ gzip: stdin: not in gzip format
│ tar: Child returned status 1
│ tar: Error is not recoverable: exiting now
│ ERROR: LoadError: failed process: Process(`tar -xvf reduce.tar.gz`, ProcessExited(2)) [2]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│  [2] pipeline_error at ./process.jl:695 [inlined]
│  [3] #run#505(::Bool, ::Function, ::Cmd) at ./process.jl:653
│  [4] run(::Cmd) at ./process.jl:651
│  [5] top-level scope at /home/kir/.julia/packages/Reduce/YlFQE/deps/build.jl:61
│  [6] include at ./boot.jl:317 [inlined]
│  [7] include_relative(::Module, ::String) at ./loading.jl:1038
│  [8] include(::Module, ::String) at ./sysimg.jl:29
│  [9] include(::String) at ./client.jl:388
│  [10] top-level scope at none:0
│ in expression starting at /home/kir/.julia/packages/Reduce/YlFQE/deps/build.jl:30
│ Building Reduce.jl with CSL binaries ... 
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
```
I think there is a problem with tar-gz file which contains Reduce. Actually, it is definitely NOT a tar-gz archive (it cannot be opened). 

Actually, this problem can be avoided, for example: I go to the site with Reduce files and manually install the latest version: Reduce-svn4717-src with tar-gz format. Then I place this archive into deps folder with the proper name "reduce.tar.gz" and commented out the line
`download(http*date[ρ]*"/linux64"*src*rsvn[ρ]*"_amd64.tgz"*dl,joinpath(wdir,rtg))`
in build.jl. 

And there is definitely a problem with the line 10 in build file:
```
global ver = read(f,String) |> parse
ERROR: MethodError: no method matching parse(::String)
```
So you have to write parse(Int, "2") for example.

**Comment by chakravala** [comment]
> I think there is a problem with tar-gz file which contains Reduce.

The download links show that this is the same `tgz` file as has always worked in the Travis CI tests. 

https://sourceforge.net/projects/reduce-algebra/files/snapshot_2018-04-06/linux64/

Perhaps the file you downloaded was corrupted, I don't believe there is an issue with the file.

> And there is definitely a problem with the line 10 in build file:

Thanks for pointing out, I don't need to rely on that build script so I didn't notice the issue, since I have a local installation of REDUCE that I compiled from source. **I will fix that**.

Note that if you have `redcsl` installed on your linux path, then that should automatically work too.

**Comment by chakravala** [comment]
Alright, so looks like the automated tests are all passing on Linux.

https://travis-ci.org/chakravala/Reduce.jl/builds/420488040
