### ISSUE TITLE
Using the SCOPE package

### ISSUE THREAD

**Issue by saschatimme** [chakravala/Reduce.jl#20]
Hey  👋 ,

I am interested in using the [SCOPE](http://www.reduce-algebra.com/reduce38-docs/scope.pdf) package in Reduce to optimize the evaluation of multivariate polynomials in my package [StaticPolynomials](https://github.com/JuliaAlgebra/StaticPolynomials.jl).

Working with the string interface I get the result I want out of REDUCE:
```julia
julia> using Reduce;
loadReduce (Free CSL version, revision 4534), 05-Apr-18 ...

julia> load_package(:SCOPE)

julia> rcall("z:=a^2*b^2+10*a^2*m^6+a^2*m^2+2*a*b*m^4+2*b^2*m^6+b^2*m^2");

julia> rcall("OPTIMIZE z:=:z")
"g2 := m*m;\ng1 := g2*g2;\nz := a*a*(g2 + b*b + 10*g2*g1) + g2*b*(2*g2*a + b*(2*g1 + 1))"
```
But I cannot find a way to express this in a way such that I can avoid strings and only work with expressions. Just a way to convert the result of the last call back to expressions would also be sufficient for me. I think there is a hacky version using find-and-replace as well as `Meta.parse`, but is there a better way dealing with this?

**Comment by chakravala** [comment]
You are lucky, because I already provided you with an `optimize` method in the `Algebra` module, but it will not work unless you call `load_package(:scope)` first, so load the package, and then it should work.
