### ISSUE TITLE
libtinfo.so.5 no such file or directory

### ISSUE THREAD

**Issue by pmcvay** [chakravala/Reduce.jl#21]
In a linux system, after `Pkg.add("Reduce")` and `Pkg.build("Reduce")`, I get the following error trying to load Reduce
```
julia> using Reduce
[ Info: Precompiling Reduce [93e0c654-6965-5f22-aba9-9c1ae6b3c259]
[ Info: Precompiling extra Reduce methods (set `ENV["REDPRE"]="0"` to disable)
/home/paul/.julia/packages/Reduce/sobXf/deps/usr/lib/reduce/cslbuild/csl/reduce: error while loading 
shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ERROR: LoadError: LoadError: IOError: write: broken pipe (EPIPE)
Stacktrace:
```

**Comment by chakravala** [comment]
This is not an issue with the Julia package, but an issue with your OS packaging for `ncurses`.

On arch linux, you could try installing the following package https://aur-dev.archlinux.org/packages/libtinfo/

But the solution depends on the specifics of your operating system, so I can't really help with that.

**Comment by cscherrer** [comment]
I have this issue as well, because Arch (or Manjaro in my case) uses libtinfo.so.6 instead.

I do see an AUR version of reduce - in the process of installing it now. Assuming I get this working, should I be able to remove the one packaged with Reduce.jl and symlink to this one? Any known issues?

**Comment by chakravala** [comment]
Yes, I am personally using the AUR version of REDUCE on my system (but I am not on manjaro)

Any locally installed version of REDUCE will be automatically detected.

**Comment by cscherrer** [comment]
> Any locally installed version of REDUCE will be automatically detected.

I hadn't even thought to try this. Now that it's installed locally, I was able to remove and then `dev Reduce`, and it seems to just work. This looks really great, thank you!

**Comment by chakravala** [comment]
< I was able to remove and then `dev Reduce`

a new release of `Reduce` has just been tagged, I think you should `free Reduce` now, unless you want to work with possible breaking changes of the internals in the future

**Comment by cscherrer** [comment]
Thoughtful of you to come back to let me know this, thank you!

**Comment by chriselrod** [comment]
I am getting the same error because I have `libtinfo.so.6` and not `libtinfo.so.5`.
I tried the AUR package for Reduce svn, but got:
```
mv: cannot stat 'src/closures.loT': No such file or directory
make[4]: Leaving directory '/home/chriselrod/Documents/AUR/reduce-svn/src/reduce-build/cslbuild/x86_64-pc-linux-gnu/libffi'
make[3]: *** [Makefile:1363: install-recursive] Error 1
make[3]: Leaving directory '/home/chriselrod/Documents/AUR/reduce-svn/src/reduce-build/cslbuild/x86_64-pc-linux-gnu/libffi'
make[2]: *** [Makefile:5365: ../include/ffi.h] Error 2
mv: cannot stat 'src/.deps/closures.Tpo': No such file or directory
make[4]: *** [Makefile:1290: src/closures.lo] Error 1
make[4]: Leaving directory '/home/chriselrod/Documents/AUR/reduce-svn/src/reduce-build/cslbuild/x86_64-pc-linux-gnu/libffi'
make[3]: *** [Makefile:1363: install-recursive] Error 1
make[3]: Leaving directory '/home/chriselrod/Documents/AUR/reduce-svn/src/reduce-build/cslbuild/x86_64-pc-linux-gnu/libffi'
make[2]: *** [Makefile:5365: ../lib/libffi.a] Error 2
ranlib libsoftfloat.a
```

**Comment by chakravala** [comment]
Try installing [ncurses5-compat-libs](https://aur.archlinux.org/packages/ncurses5-compat-libs/) from the AUR first

**Comment by chriselrod** [comment]
I am still getting similar "no such file or directory" errors.

**Comment by chakravala** [comment]
Thanks for figuring it out, is it an issue with the AUR `PKGBUILD` script? or is it an upstream issue?

in either case, I recommend  submitting a request to AUR or to the Sourceforge discussion forum for REDUCE itself if it is an upstream issue, they are usually both responsive
