### ISSUE TITLE
Conditional application of rewrite (substitution) rules?

### ISSUE THREAD

**Issue by pitsianis** [chakravala/Reduce.jl#24]
Is there a way to apply sets of rewrite rules conditionally (based on the unification of the pattern variables of the rules)? Can you give an example?

The introspection of Julia together with powerful symbolic math manipulation makes it a very powerful platform for numerical metaprogramming. 

I have been dreaming of a way to, for example, have a general matrix multiplication routine and get the high-performance blocking automatically. But also produce specializations automatically, for triangular, banded, symmetric matrices, etc.

**Comment by chakravala** [comment]
> Is there a way to apply sets of rewrite rules conditionally (based on the unification of the pattern variables of the rules)? Can you give an example?

It's not clear to me what you are asking, I recommend you ask the question on the [REDUCE user forum](https://sourceforge.net/p/reduce-algebra/discussion/) if it is specific to the upstream language, this repository is only for maintaining an interface for the language

**Comment by pitsianis** [comment]
Thank you for the quick reply. I will ask at the REDUCE user forum.

Do you come to Duke? I see you are near by.

Nikos

**Comment by chakravala** [comment]
At Duke there is a much older mathematician, who coincidentally has the same name as I do, but we are not the same individual. Although I am not associated with Duke, I have visited Duke Gardens many times.

Also, if you haven't already done so, join the [Julia discourse](https://discourse.julialang.org). Lots of helpful people on there who discuss specialization for general matrix multiplication, which is handled with multiple-dispatch.

**Comment by pitsianis** [comment]
I will be happy to offer coffee next time you come to campus. 

For my PhD, ages ago I had to resort to several programming languages to use term rewriting for code generation. Model in MATLAB, manipulate in Mma/Maple, export to C. With a tool like yours in Julia it is tantalizing close that the whole thing can be done under the same language.

See the second part of
The Kronecker Product in Approximation and Fast Transform Generation <https://users.cs.duke.edu/~nikos/reprints/T-001-KronProdApprox.pdf>
if you are curious to see how term rewriting can be used in the generation of efficient signal processing implementations.

Best regards,
N

**Comment by chakravala** [comment]
Thanks for sharing the thesis, it so happens this week I am studying the Frobenius norm in relation to computing the generalized logarithm function for multivectors with my other package [Grassmann.jl](https://github.com/chakravala/Grassmann.jl) and it also happens that I intend on collaborating with @arsenovic on electric circuits and signal processing

Please send me an email if you wish to have a private communication, I have sent you an email
