### ISSUE TITLE
Incorrect parsing with `f1` due to floating point

### ISSUE THREAD

**Issue by rjrosati** [chakravala/Reduce.jl#25]
Hi,
I'm having some trouble using the exponential function, see below:

```
julia> using Reduce
Reduce (Free CSL version, revision 4534), 05-Apr-18 ...

julia> @force using Reduce.Algebra

julia> f = :f1
:f1

julia> a = exp(-6*f)
:(1 / ℯ ^ 60.0f0)

julia> Algebra.on(:rounded)

julia> b = sub("f1=1.0",a)
8.7565107627e-27

julia> exp(-6.0)
0.0024787521766663585
```

To me it looks like some kind of parsing error, since a symbol without a number (i.e. `f = :f`) works as expected.

**Comment by chakravala** [comment]
Ahh, interesting, looks like the `f1` gets parsed as a floating point value instead of a symbol there.

My initial recommendation is to use a different variable letter.

**Comment by rjrosati** [comment]
Ah that makes sense, thanks. I'll avoid appending digits to the end of my `f`'s.
I noticed the same problem happens with `e`'s (i.e. `exp(-6*:e2)` gets parsed as `exp(-600)` ). And I suppose it could happen with `b`, `o`, `x`, and `p` too since those are all valid parts of `Int` or `Float` literals.

**Comment by chakravala** [comment]
Alright, then I'm marking this as #wontfix and closing the issue.
