### ISSUE TITLE
promotion fails for subtyping

### ISSUE THREAD

**Issue by Roger-luo** [chakravala/Reduce.jl#26]
```jl
@subtype SymReal <: Real

SymReal(:x) * im
```

I'm wondering if there should be some specialization for subtypes of `Real` etc.?

**Comment by chakravala** [comment]
@Roger-luo this issue has now been resolved, let me know if you find another bug

```Julia

julia> Reduce.@subtype SymReal <: Real

julia> SymReal(:x) * im
0 + x*im
```
