### ISSUE TITLE
[Upstream] Syntax error with sqrt of rational expression

### ISSUE THREAD

**Issue by xaellison** [chakravala/Reduce.jl#27]
I was checking out Reduce's capabilities for partial differentiation and I was excited since for my use case it's better than automatic differentiation. Unfortunately, it seems to crash for moderately complex expressions. 

I've included a MWE below which shows a trivial working example (case 0), two complex working examples (cases 1 and 2), and finally a slightly more complex version which fails (case 3).

```
julia> :(df(x^2+t^2, x)) |> rcall
:(2x)

julia> :(df((1 - ((a + b*t)^2*(c*v1 + d*v2 + e*v3))/(f)^2)^(1/2), t)) |> rcall
:((-((d * v2 + ℯ * v3 + c * v1)) * (a + b * t) * b) / (sqrt(-((d * v2 + ℯ * v3 + c * v1)) * (a + b * t) ^ 2 + f ^ 2) * abs(f)))

julia> :(df((1 - ((a + b*t)^2*(c*v1 + d*v2 + e*v3))/(t)^2)^(1/2), t)) |> rcall
:(((a * c * v1 + a * d * v2 + a * ℯ * v3 + b * c * t * v1 + b * d * t * v2 + b * ℯ * t * v3) * a) / (sqrt(-((d * v2 + ℯ * v3 + c * v1)) * (a + b * t) ^ 2 + t ^ 2) * abs(t) * t))

julia> :(df((1 - ((a + b*t)^2*(c*v1 + d*v2 + e*v3))/(f+t)^2)^(1/2), t)) |> rcall
ERROR: Reduce: 
***** Syntax error: f(
+++ Error attempt to take car of an atom: 1
Stacktrace:
 [1] ReduceCheck at /Users/alex/.julia/packages/Reduce/TI9IX/src/Reduce.jl:60 [inlined]
 [2] read(::Reduce.PSL) at /Users/alex/.julia/packages/Reduce/TI9IX/src/Reduce.jl:95
 [3] readsp at /Users/alex/.julia/packages/Reduce/TI9IX/src/Reduce.jl:99 [inlined]
 [4] #rcall#40(::Array{Symbol,1}, ::Array{Symbol,1}, ::Function, ::RExpr) at /Users/alex/.julia/packages/Reduce/TI9IX/src/rexpr.jl:464
 [5] #rcall at ./none:0 [inlined]
 [6] #rcall#41(::Array{Symbol,1}, ::Array{Symbol,1}, ::Function, ::Expr) at /Users/alex/.julia/packages/Reduce/TI9IX/src/rexpr.jl:497
 [7] rcall at /Users/alex/.julia/packages/Reduce/TI9IX/src/rexpr.jl:497 [inlined]
 [8] |>(::Expr, ::typeof(rcall)) at ./operators.jl:813
 [9] top-level scope at none:0
julia> 

```
The right most variable to appear in case 1 is `f`. Case two replaces `f` by `t`. Case 3 puts in that position `f + t`, which seems to cause the failure. 

Are there known limitations on the complexity of the AST for operations like `df`?

**Comment by rjrosati** [comment]
This doesn't seem to be a complexity issue, since replacing the square in the denominator with a new symbol works:

    julia> :(df((1 - ((a + b*t)^2*(c*v1 + d*v2 + e*v3))/(f+t)^q)^(1/2), t)) |> rcall

**Comment by xaellison** [comment]
Fascinating... it seems to be a problem with `sqrt` and/or `abs`. This is probably what I get for tinkering with Mathematica output and piping it in. I can get the same error for some expressions on `Algebra.optimize`, too.

As a workaround, substituting specific powers for a variable may be sufficient. It also fixed the case I could produce for `optimize`. That doesn't mean it shouldn't work in the less general case though, right?

**Comment by chakravala** [comment]
Alright, so I made your minimum working example smaller:
```Julia
julia> :((1/(f+t)^2)^(1/2)) |> RExpr
Error showing value of type RExpr:
ERROR: Reduce: 

***** Syntax error: f(
+++ Error attempt to take car of an atom: 1
```
As you can see next, the AST parsing is not the problem. The Error message also makes this clear, this is an internal syntax error from the REDUCE language.
```Julia
julia> :((1/(f+t)^2)^(1/2)) |> RExpr |> string
"^(/(1,^(+(f,t),2)),/(1,2))"
```
However, the following example seems to work (it seems to error for rational expressions):
```Julia
julia> :(((f+t)^2)^(1/2)) |> RExpr

abs(f + t)
```
Since this issue is outside of the scope of my repository, I opened a [bug report](https://sourceforge.net/p/reduce-algebra/bugs/106/) on sourceforge.

**Comment by chakravala** [comment]
@xaellison, if you `dev Reduce` to get the latest `master` branch of v1.2.3 this issue is resolved:
```Julia
pkg> dev Reduce

pkg> build Reduce

julia> using Reduce
Reduce (Free CSL version, revision 5151), 02-Oct-19 ...

julia> Algebra.df(:((1 - ((a + b*t)^2*(c*v1 + d*v2 + e*v3))/(f+t)^2)^(1/2)), :t)
:((((d * v2 + ℯ * v3 + c * v1) * (a + b * t) ^ 2 - (f + t) ^ 2) - ((d * v2 + ℯ * v3 + c * v1) * (a + b * t) * b - (f + t)) * (f + t)) / (sqrt(-((d * v2 + ℯ * v3 + c * v1)) * (a + b * t) ^ 2 + (f + t) ^ 2) * (f + t) * abs(f + t)))
```
Currently I am using revision 5151, while the build script should fetch revision 5122. Both of these newer revisions of the upstream REDUCE program do not have this issue anymore.

**Comment by xaellison** [comment]
@chakravala thanks! That resolves the error with that input
