### ISSUE TITLE
(documentation) `rlet` function parameters

### ISSUE THREAD

**Issue by lucasvreis** [chakravala/Reduce.jl#33]
Hi,
The documentation for `rlet` states that it takes an `expr` as a parameter, but from my understanding it only takes a list of substitutions in a Dict or varargs in Pair form:

https://github.com/chakravala/Reduce.jl/blob/fcc9459a099b9bab2ef2e958438b92903061d92d/src/unary.jl#L211-L213

**Comment by lucasvreis** [comment]
By the way, on the same section, somebody forgot to close a coding environment on the docs for `clear`:

https://github.com/chakravala/Reduce.jl/blob/fcc9459a099b9bab2ef2e958438b92903061d92d/src/args.jl#L1010-L1016

**Comment by chakravala** [comment]
Thanks, you are welcome to make a pull request next time and let me know of any other issues.
