### ISSUE TITLE
StackOverflowError when evaluating `repart` and `impart` of `im` unit

### ISSUE THREAD

**Issue by lucasvreis** [chakravala/Reduce.jl#34]
Hello,
When I evaluate `Algebra.repart(im)` or `Algebra.impart(im)`, I get a `StackOverflowError`. I can fix it by writing `1im` in the argument, but the problem is that sometimes the manipulation of other expressions produce the symbol `im`, so I can't use `eval` on them.

I don't know how to fix this, so thanks in advance.

**Comment by chakravala** [comment]
The issue should be fixed now.
