### ISSUE TITLE
Substituting single expression without using a tuple.

### ISSUE THREAD

**Issue by ghyatzo** [chakravala/Reduce.jl#35]
Hello,

I've encountered the following issue:
`Algebra.sub(:(r=1), expr)` that returns an error where sub does not have the method `sub(::Expr, expr)`

Instead by writing
`Algebra.sub((:(r=1),), expr)` hence putting `:(r=1)` inside a tuple works .

I actually went to check the source code and the `sub` function only has methods for tuples of expressions.
I personally find the notation `(:(r=1),)` rather confusing. Can't something like the following be implemented?
`Algebra.sub(s::Expr, expr) = Algebra.sub(string(list(s)), expr)`.

I tested it and it works 
Any particular reason why the single expression is not implemented? 

Thanks

**Comment by chakravala** [comment]
The reason why it's not implemented is because it's not my job to predict every convenience that this package might provide, you are welcome to make a pull request or I can add the feature when I get around to it.

**Comment by ghyatzo** [comment]
Wasn’t trying to sound condescending. I am sorry. I am more than happy to make a pull request. Just wanted to make sure this was something not already considered that would otherwise break something. 

cheers.
