### ISSUE TITLE
InitError: IOError  redcsl

### ISSUE THREAD

**Issue by zhanghg1983** [chakravala/Reduce.jl#47]
when 
I type :using Reduce
I recieve:  IOError: could not spawn `/home/zhg/.julia/packages/Reduce/1n3pM/src/../deps/usr/bin/redcsl`: no such file or directory (ENOENT)
IOError: could not spawn `redcsl`: no such file or directory (ENOENT)
So anyone can do me a favor what,s wrong 
My OS :manajro xcfe 
julia :1.5.3
Thank you

**Comment by chakravala** [comment]
Did you try `pkg> build Reduce` yet?

**Comment by zhanghg1983** [comment]
Thank you very much,it woks
