### ISSUE TITLE
No documentation about how to get formula typesetting on Pluto.jl

### ISSUE THREAD

**Issue by adamryczkowski** [chakravala/Reduce.jl#50]
Since Reduce already has LaTeX interface for input and output I assume it is possible to get the beautiful equation rendering on Pluto.jl. I could not get any hint on how to do that. Please advise me on that.

**Comment by chakravala** [comment]
I have never used Pluto.jl yet and never tested compatibility with Reduce.jl yet, you are welcome to contribute this feature, or i may add it someday when i feel like looking into it.

**Comment by adamryczkowski** [comment]
Thank you for the answer.
